#this updates and stores required libs in this location

#pip-chill --no-version > conda-requirements.txt
#heroku buildpacks:set https://github.com/teamupstart/conda-buildpack.git -a stock-stats


#source activate C:\\Users\\deepakk\\Anaconda3\\envs\\drk3931-stocks
#conda env update --prefix /opt/anaconda3/envs/drk3931-stocks --file environment.yml  --prune
#conda env update --prefix C:\\Users\\deepakk\\Anaconda3\\envs\\drk3931-stocks --file environment.yml  --prune

name: drk3931-stocks
channels:
  - anaconda
  - conda-forge
dependencies:
- python>=3.5
- matplotlib
- pandas
- pandas-datareader
- flask
- mpld3
- pip
- pip:
  - gunicorn


